#!/usr/bin/env python3
"""
Generate publication-ready figures for the Human-Light redesign.

Produces:
  * results/redesign/figures/fig_pipeline_four_layer.{pdf,png}
  * results/redesign/figures/fig_failure_case_panel.{pdf,png}

Existing figures (rating distributions, prediction-vs-human, saturation curves,
feature-importance bars) are generated by their respective analysis scripts.
"""

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
from pathlib import Path
from scipy import stats

ROOT = Path(__file__).resolve().parents[2]
FIGURES = ROOT / "results" / "redesign" / "figures"
TABLES = ROOT / "results" / "redesign" / "tables"
FIGURES.mkdir(parents=True, exist_ok=True)

plt.rcParams["font.family"] = "Arial"
plt.rcParams["axes.unicode_minus"] = False

COLORS = {
    "A": "#4C78A8",
    "B": "#F58518",
    "C": "#E45756",
    "D": "#72B7B2",
}


def draw_pipeline():
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.set_xlim(0, 10)
    ax.set_ylim(0, 8)
    ax.axis("off")

    layers = [
        ("Layer A\nLarge-scale proxy development", "17,337 images\ncomputational proxy targets\nfeature engineering & model selection", COLORS["A"], 6.5),
        ("Layer B\nFrozen human validation", "100 images, 30 raters\npre-fitted model applied once\nSpearman / Kendall with CIs", COLORS["B"], 4.8),
        ("Layer C\nHuman-efficiency analysis", "Rater and image saturation\nlabel-efficiency curves", COLORS["C"], 3.1),
        ("Layer D\nOptional calibration", "Small-sample linear mapping\nheld-out evaluation", COLORS["D"], 1.4),
    ]

    boxes = []
    for title, body, color, y in layers:
        box = FancyBboxPatch(
            (1, y), 8, 1.2,
            boxstyle="round,pad=0.05,rounding_size=0.15",
            facecolor=color,
            edgecolor="black",
            alpha=0.25,
            linewidth=1.5,
        )
        ax.add_patch(box)
        ax.text(5, y + 0.85, title, ha="center", va="center", fontsize=12, weight="bold", color="black")
        ax.text(5, y + 0.35, body, ha="center", va="center", fontsize=9, color="black")
        boxes.append(box)

    for i in range(len(boxes) - 1):
        arrow = FancyArrowPatch(
            (5, layers[i][3] - 0.05),
            (5, layers[i + 1][3] + 1.25),
            arrowstyle="-|>",
            mutation_scale=20,
            color="black",
            lw=1.5,
        )
        ax.add_patch(arrow)

    ax.set_title("Four-layer Human-Light Study Pipeline", fontsize=14, weight="bold", y=0.98)
    out_png = FIGURES / "fig_pipeline_four_layer.png"
    out_pdf = FIGURES / "fig_pipeline_four_layer.pdf"
    fig.savefig(out_png, dpi=300, bbox_inches="tight")
    fig.savefig(out_pdf, dpi=300, bbox_inches="tight")
    print(f"Saved {out_png} and {out_pdf}")


def draw_failure_panel():
    frozen = pd.read_csv(TABLES / "frozen_human_validation.csv")
    failure = pd.read_csv(TABLES / "failure_cases.csv")

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Left: overall prediction vs human mean per dimension
    ax = axes[0]
    human = pd.read_csv(TABLES / "human_mean_ratings.csv")
    feats = pd.read_csv(ROOT / "data" / "features" / "traditional_features.csv")
    df = human.merge(feats, on="image_id", how="inner")

    import pickle
    with open(ROOT / "results" / "redesign" / "models" / "frozen_primary_model.pkl", "rb") as f:
        frozen_model = pickle.load(f)
    feature_cols = frozen_model["feature_cols"]
    X = df[feature_cols].values

    for dim in ["complexity", "beauty", "order", "emotion"]:
        y_true = df[dim].values
        y_pred = frozen_model["models"][dim].predict(X)
        ax.scatter(y_true, y_pred, alpha=0.5, s=30, label=dim)
    ax.plot([1, 7], [1, 7], "k--", lw=1)
    ax.set_xlabel("Human mean rating")
    ax.set_ylabel("Frozen model prediction")
    ax.set_title("Prediction vs. human mean (all dimensions)")
    ax.legend(title="Dimension", loc="lower right")
    ax.set_xlim(1, 7)
    ax.set_ylim(1, 7)

    # Right: top absolute errors from failure_cases.csv
    ax = axes[1]
    if not failure.empty:
        failure = failure.sort_values("abs_error", ascending=False).head(10)
        labels = [f"{r['image_id']}" for _, r in failure.iterrows()]
        ax.barh(labels[::-1], failure["abs_error"].values[::-1], color=COLORS["C"])
        ax.set_xlabel("Absolute error (human mean - frozen prediction)")
        ax.set_title("Largest absolute errors: order dimension")
    else:
        ax.text(0.5, 0.5, "No failure cases recorded", ha="center", va="center", transform=ax.transAxes)
        ax.set_title("Failure cases")

    plt.tight_layout()
    out_png = FIGURES / "fig_failure_case_panel.png"
    out_pdf = FIGURES / "fig_failure_case_panel.pdf"
    fig.savefig(out_png, dpi=300, bbox_inches="tight")
    fig.savefig(out_pdf, dpi=300, bbox_inches="tight")
    print(f"Saved {out_png} and {out_pdf}")


def main():
    draw_pipeline()
    draw_failure_panel()
    print("All redesign figures generated.")


if __name__ == "__main__":
    main()
