#!/usr/bin/env python3
"""
Preflight check for the no-human pipeline.

Reports missing inputs and environment problems before expensive computation.
"""
import argparse
import importlib.metadata as im
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_PACKAGES = [
    "numpy", "pandas", "scipy", "matplotlib", "seaborn", "scikit-learn",
    "scikit-image", "opencv-python", "Pillow", "torch", "torchvision",
    "transformers", "xgboost", "lightgbm", "shap", "statsmodels",
    "pingouin", "tqdm", "colorspacious", "easyocr", "joblib",
    "huggingface_hub", "umap-learn",
]

PUBLIC_DEMO_REQUIRED_PACKAGES = [
    "numpy", "pandas", "scipy", "matplotlib", "seaborn", "scikit-learn",
    "scikit-image", "opencv-python", "Pillow", "statsmodels",
    "pingouin", "tqdm", "PyYAML", "joblib",
]

RESTRICTED_INPUTS = [
    ROOT / "data" / "processed" / "no_human_image_manifest.csv",
    ROOT / "data" / "features" / "traditional_features.csv",
    ROOT / "data" / "features" / "enhanced_features.csv",
    ROOT / "data" / "features" / "deep" / "image_ids.csv",
    ROOT / "data" / "features" / "deep" / "resnet50_features.npy",
    ROOT / "configs" / "no_human_design.yaml",
    ROOT / "configs" / "no_human_stability_transforms.yaml",
]

PUBLIC_DEMO_INPUTS = [
    ROOT / "configs" / "public_demo.yaml",
    ROOT / "synthetic_benchmark" / "manifests" / "image_manifest.csv",
    ROOT / "synthetic_benchmark" / "metadata" / "target_metadata.csv",
    ROOT / "synthetic_benchmark" / "metadata" / "synthetic_traditional_features.csv",
]


def main():
    parser = argparse.ArgumentParser(description="Preflight check for the no-human pipeline.")
    parser.add_argument("--mode", choices=["restricted", "public-demo"], default="restricted",
                        help="Which inputs to validate (default: restricted)")
    args = parser.parse_args()

    issues = []
    print(f"Python: {sys.version}")
    if sys.version_info < (3, 9):
        issues.append("Python 3.9+ is required")

    packages_to_check = PUBLIC_DEMO_REQUIRED_PACKAGES if args.mode == "public-demo" else REQUIRED_PACKAGES
    for pkg in packages_to_check:
        try:
            ver = im.version(pkg)
            print(f"  {pkg}: {ver}")
        except Exception:
            issues.append(f"missing package: {pkg}")

    required_inputs = PUBLIC_DEMO_INPUTS if args.mode == "public-demo" else RESTRICTED_INPUTS
    for path in required_inputs:
        if path.exists():
            print(f"  [OK] {path.relative_to(ROOT)}")
        else:
            issues.append(f"missing input: {path.relative_to(ROOT)}")

    if args.mode == "public-demo":
        manifest = ROOT / "synthetic_benchmark" / "manifests" / "image_manifest.csv"
        path_col = "image_path"
    else:
        manifest = ROOT / "data" / "processed" / "no_human_image_manifest.csv"
        path_col = "relative_path"

    if manifest.exists():
        import csv
        with open(manifest, newline="", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
        print(f"  image manifest: {len(rows)} images")
        if rows:
            first = rows[0].get(path_col)
            if first:
                img_path = ROOT / first
                if not img_path.exists():
                    if args.mode == "public-demo":
                        print(f"  [INFO] first image file missing (will be regenerated by download_data.py): {first}")
                    else:
                        issues.append(f"first image file missing: {first}")

    if issues:
        print("\nPreflight issues:")
        for i in issues:
            print(f"  - {i}")
        sys.exit(1)
    print("\nPreflight passed.")


if __name__ == "__main__":
    main()
